drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    role varchar(20),
    primary key (id)
);

insert into member(name, role) values('John', 'writer');
insert into member(name, role) values('James', 'approver');
insert into member(name, role) values('Tom', 'approver');

drop table if exists document CASCADE;
create table document
(
    id bigint generated by default as identity,
    title varchar(255) not null,
    content varchar(255) not null,
    status varchar(20) not null,
    creator_id bigint not null,
    approver_id bigint not null,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp on update current_timestamp,
    primary key (id)
);